import type { Project, Task, StatusConfig } from '../types';
import { sanitizeFileName, isTerminalStatus } from '../utils';
import { appendYaml, stripAutoGeneratedContent, FRONTMATTER_KEY, TASK_FRONTMATTER_KEY } from './YamlParser';

// ─── Changelog ──────────────────────────────────────────────────────────────

const TASK_TRACKED_FIELDS: (keyof Task)[] = [
  'title', 'status', 'priority', 'type', 'start', 'due', 'progress', 'assignees', 'tags',
];

const PROJECT_TRACKED_FIELDS: (keyof Project)[] = [
  'title', 'status', 'priority', 'startDate', 'endDate', 'client', 'owner', 'portfolio', 'ganttColor',
];

function formatVal(v: unknown): string {
  if (v === undefined || v === null || v === '') return '""';
  if (Array.isArray(v)) return `[${v.map(x => `"${x}"`).join(', ')}]`;
  return `"${v}"`;
}

function arraysEqual(a: unknown[], b: unknown[]): boolean {
  return a.length === b.length && a.every((x, i) => x === b[i]);
}

function valuesEqual(a: unknown, b: unknown): boolean {
  if (Array.isArray(a) && Array.isArray(b)) return arraysEqual(a, b);
  return a === b;
}

/** Append new changelog entries to a description body. */
export function appendChangelogEntries(description: string, entries: string[]): string {
  if (!entries.length) return description;
  const today = new Date().toISOString().slice(0, 10);
  const newLines = entries.map(e => `- ${today}: ${e}`).join('\n');

  const sectionMatch = description.match(/^## Changelog\s*$/m);
  if (sectionMatch) {
    // Insert after the ## Changelog heading
    const idx = description.indexOf(sectionMatch[0]) + sectionMatch[0].length;
    return description.slice(0, idx) + '\n' + newLines + description.slice(idx);
  }
  // No changelog section yet — append it
  const base = description.trimEnd();
  return (base ? base + '\n\n' : '') + '## Changelog\n' + newLines;
}

/** Compute changelog entries between an old and new task. */
export function computeTaskChangelog(oldTask: Task, newTask: Task): string[] {
  const entries: string[] = [];
  for (const field of TASK_TRACKED_FIELDS) {
    const oldVal = oldTask[field];
    const newVal = newTask[field];
    if (!valuesEqual(oldVal, newVal)) {
      entries.push(`${field}: ${formatVal(oldVal)} → ${formatVal(newVal)}`);
    }
  }
  return entries;
}

/** Compute changelog entries between an old and new project. */
export function computeProjectChangelog(oldProject: Project, newProject: Project): string[] {
  const entries: string[] = [];
  for (const field of PROJECT_TRACKED_FIELDS) {
    const oldVal = oldProject[field];
    const newVal = newProject[field];
    if (!valuesEqual(oldVal, newVal)) {
      entries.push(`${field}: ${formatVal(oldVal)} → ${formatVal(newVal)}`);
    }
  }
  return entries;
}

// ─── Serialize ──────────────────────────────────────────────────────────────

export function serializeProject(project: Project, statuses: StatusConfig[] = []): string {
  const taskIds = project.tasks.map(t => t.id);

  const fm: Record<string, unknown> = {
    [FRONTMATTER_KEY]: true,
    id: project.id,
    title: project.title,
    description: project.description,
    color: project.color,
    icon: project.icon,
    taskIds,
    customFields: project.customFields,
    teamMembers: project.teamMembers,
    savedViews: project.savedViews.length ? project.savedViews : [],
    createdAt: project.createdAt,
    updatedAt: project.updatedAt,
  };
  // optional project metadata — only write when set
  if (project.status)                  fm.status       = project.status;
  if (project.startDate)               fm.startDate    = project.startDate;
  if (project.endDate)                 fm.endDate      = project.endDate;
  if (project.client)                  fm.client       = project.client;
  if (project.portfolio)               fm.portfolio    = project.portfolio;
  if (project.owner)                   fm.owner        = project.owner;
  if (project.priority)                fm.priority     = project.priority;
  if (project.budget !== undefined)    fm.budget       = project.budget;
  if (project.hourlyRate !== undefined) fm.hourlyRate  = project.hourlyRate;
  if (project.currency)                fm.currency     = project.currency;
  if (project.sortOrder !== undefined) fm.sortOrder    = project.sortOrder;
  if (project.ganttColor)              fm.ganttColor   = project.ganttColor;

  const yamlLines: string[] = ['---'];
  appendYaml(yamlLines, fm, 0);
  yamlLines.push('---');
  yamlLines.push('');
  yamlLines.push(`# ${project.icon} ${project.title}`);
  yamlLines.push('');
  if (project.description) {
    yamlLines.push(project.description);
    yamlLines.push('');
  }
  if (project.tasks.length) {
    yamlLines.push('## Tasks');
    for (const t of project.tasks) {
      if (t.filePath) {
        const basename = t.filePath.replace(/^.*\//, '').replace(/\.md$/, '');
        const check = isTerminalStatus(t.status, statuses) ? 'x' : ' ';
        yamlLines.push(`- [${check}] [[${basename}|${t.title}]]`);
      }
    }
    yamlLines.push('');
  }

  return yamlLines.join('\n');
}

export function serializeTask(
  task: Task,
  project: Project,
  parentTask: Task | null,
  statuses: StatusConfig[] = [],
): string {
  const subtaskIds = task.subtasks.map(s => s.id);
  const fm: Record<string, unknown> = {
    [TASK_FRONTMATTER_KEY]: true,
    projectId: project.id,
    parentId: parentTask?.id ?? null,
    id: task.id,
    title: task.title,
    type: task.type,
    status: task.status,
    priority: task.priority,
    start: task.start,
    due: task.due,
    progress: task.progress,
    assignees: task.assignees,
    tags: task.tags,
    subtaskIds,
    dependencies: task.dependencies,
    collapsed: task.collapsed,
    createdAt: task.createdAt,
    updatedAt: task.updatedAt,
  };
  if (task.recurrence) fm.recurrence = task.recurrence;
  if (task.timeEstimate !== undefined) fm.timeEstimate = task.timeEstimate;
  if (task.timeLogs?.length) fm.timeLogs = task.timeLogs;
  if (Object.keys(task.customFields).length) fm.customFields = task.customFields;

  const yamlLines: string[] = ['---'];
  appendYaml(yamlLines, fm, 0);
  yamlLines.push('---');
  yamlLines.push('');
  const cleanDesc = stripAutoGeneratedContent(task.description);
  if (cleanDesc) {
    yamlLines.push(cleanDesc);
    yamlLines.push('');
  }

  if (parentTask?.filePath) {
    const parentBasename = parentTask.filePath.replace(/^.*\//, '').replace(/\.md$/, '');
    yamlLines.push(`Parent: [[${parentBasename}|${parentTask.title}]]`);
  } else {
    const projectBasename = project.filePath.replace(/^.*\//, '').replace(/\.md$/, '');
    yamlLines.push(`Project: [[${projectBasename}|${project.title}]]`);
  }

  if (task.subtasks.length) {
    yamlLines.push('');
    yamlLines.push('## Subtasks');
    for (const sub of task.subtasks) {
      const subSlug = sanitizeFileName(sub.title).toLowerCase().replace(/\s+/g, '-').slice(0, 40);
      const subBasename = `${subSlug}-${sub.id.slice(0, 8)}`;
      const check = isTerminalStatus(sub.status, statuses) ? 'x' : ' ';
      yamlLines.push(`- [${check}] [[${subBasename}|${sub.title}]]`);
    }
  }

  return yamlLines.join('\n');
}

/** Build the file path for a task .md file */
export function taskFilePath(taskTitle: string, taskId: string, folder: string): string {
  const slug = sanitizeFileName(taskTitle).toLowerCase().replace(/\s+/g, '-').slice(0, 40);
  return `${folder}/${slug}-${taskId.slice(0, 8)}.md`;
}
